# Generated by Django 4.1 on 2022-08-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CadastroModel",
            fields=[
                (
                    "nome",
                    models.CharField(max_length=254, verbose_name="Nome completo"),
                ),
                (
                    "sexo",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Feminino")],
                        max_length=1,
                        verbose_name="Sexo",
                    ),
                ),
                ("nascimento", models.DateField(verbose_name="Data de Nascimento")),
                ("rg", models.CharField(max_length=9, verbose_name="Identidade")),
                (
                    "cpf",
                    models.CharField(
                        max_length=11,
                        primary_key=True,
                        serialize=False,
                        verbose_name="CPF",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, unique=True, verbose_name="E-Mail"
                    ),
                ),
                ("telefone", models.CharField(max_length=14, verbose_name="Telefone")),
                (
                    "pai",
                    models.CharField(
                        blank=True, max_length=254, verbose_name="Nome do pai"
                    ),
                ),
                ("mae", models.CharField(max_length=254, verbose_name="Nome da mãe")),
                ("endereco", models.CharField(max_length=254, verbose_name="Endereço")),
                (
                    "cargo",
                    models.CharField(
                        choices=[
                            ("SENIOR", "Sênior"),
                            ("PLENO", "Pleno"),
                            ("JUNIOR", "Júnior"),
                        ],
                        max_length=6,
                        verbose_name="Cargo",
                    ),
                ),
                (
                    "salario",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Salário R$"
                    ),
                ),
                ("admissao", models.DateField(verbose_name="Admissão")),
                ("demissao", models.DateField(verbose_name="Demitido")),
            ],
        ),
    ]
