# Generated by Django 4.1 on 2022-08-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cadastromodel",
            name="admissao",
            field=models.DateField(blank=True, verbose_name="Admissão"),
        ),
        migrations.AlterField(
            model_name="cadastromodel",
            name="demissao",
            field=models.DateField(blank=True, verbose_name="Demitido"),
        ),
        migrations.AlterField(
            model_name="cadastromodel",
            name="salario",
            field=models.DecimalField(
                decimal_places=2, max_digits=8, verbose_name="Salário R$"
            ),
        ),
    ]
