# Generated by Django 4.1 on 2022-08-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0002_alter_cadastromodel_admissao_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cadastromodel",
            name="admissao",
            field=models.DateField(blank=True, null=True, verbose_name="Admissão"),
        ),
        migrations.AlterField(
            model_name="cadastromodel",
            name="demissao",
            field=models.DateField(blank=True, null=True, verbose_name="Demitido"),
        ),
    ]
