# Generated by Django 4.1 on 2022-08-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0003_alter_cadastromodel_admissao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cadastromodel",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cadastromodel",
            name="cpf",
            field=models.CharField(max_length=11, unique=True, verbose_name="CPF"),
        ),
    ]
