# Generated by Django 4.1 on 2022-08-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0004_cadastromodel_id_alter_cadastromodel_cpf"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cadastromodel",
            options={
                "verbose_name": "Funcionário",
                "verbose_name_plural": "Funcionários",
            },
        ),
        migrations.AlterField(
            model_name="cadastromodel",
            name="cargo",
            field=models.CharField(
                choices=[
                    ("SENIOR", "Sênior"),
                    ("PLENO", "Pleno"),
                    ("JUNIOR", "Júnior"),
                ],
                default="JUNIOR",
                max_length=6,
                verbose_name="Cargo",
            ),
        ),
    ]
