# Generated by Django 4.1 on 2022-08-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0006_alter_cadastromodel_cargo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cadastromodel",
            name="cargo",
            field=models.CharField(
                choices=[
                    ("Júnior", "JUNIOR"),
                    ("Pleno", "PLENO"),
                    ("Sênior", "SENIOR"),
                ],
                max_length=6,
                verbose_name="Cargo",
            ),
        ),
    ]
