# Generated by Django 4.1 on 2022-08-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0007_alter_cadastromodel_cargo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cadastromodel",
            name="cargo",
            field=models.CharField(max_length=8, verbose_name="Cargo"),
        ),
        migrations.AlterField(
            model_name="cadastromodel",
            name="sexo",
            field=models.CharField(max_length=10, verbose_name="Sexo"),
        ),
    ]
