# Generated by Django 4.1 on 2022-08-21 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0009_remove_cadastromodel_demissao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cadastromodel",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="E-Mail"),
        ),
    ]
