# Generated by Django 4.1 on 2022-08-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0010_alter_cadastromodel_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cadastromodel",
            name="cargo",
            field=models.CharField(max_length=20, verbose_name="Cargo"),
        ),
    ]
